### ISSUE TITLE
Support skipping blank lines and inline comments

### ISSUE THREAD

**Issue by cajmandersson** [cajmandersson/siml#5]
Ensure the tokenizer can skip over irrelevant lines such as empty lines and comments, so that the resulting token stream only contains meaningful tokens.

---

### What to build

Update the `Tokenizer` to:

- Skip lines that are empty or contain only whitespace
- Skip lines that start with `#` after trimming leading spaces
- Optionally (not required now), retain comments as metadata if needed later for documentation purposes

---

### Why it matters

Blank lines and comments are not significant in SIML but are common in real-world `.siml` files for readability. The tokenizer should ignore these lines cleanly and not emit any tokens or errors from them.

---

### Example

From this input:

```yaml
# Simulation config
config:
  max_ticks: 5  # small for testing

# initial state
state:
  - tick: 0
```
